# Generated by Django 5.1.1 on 2024-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=20)),
                ('car_name', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('Dhaka', 'Khulna'), ('Barisal', 'Rajshahi'), ('Kumellah', 'Sylleat'), ('Chittagong', 'projpur')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
